version: '3'
services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000  # ホストマシンのポート 8000 を、docker内のポート 8000 に接続する
    environment:
      - WATCHFILES_FORCE_POLLING=true  # 環境によってホットリロードのために必要
    
